before_script:
  - pip install tox setuptools

stages:
  - test

py27-django18:
  stage: test
  image: python:2.7
  script: tox -e py27-django18
py33-django18:
  stage: test
  image: python:3.3
  script: tox -e py33-django18
py34-django18:
  stage: test
  image: python:3.4
  script: tox -e py34-django18
py35-django18:
  stage: test
  image: python:3.5
  script: tox -e py35-django18
py36-django18:
  stage: test
  image: python:3.6
  script: tox -e py36-django18
py27-django19:
  stage: test
  image: python:2.7
  script: tox -e py27-django19
py34-django19:
  stage: test
  image: python:3.4
  script: tox -e py34-django19
py35-django19:
  stage: test
  image: python:3.5
  script: tox -e py35-django19
py36-django19:
  stage: test
  image: python:3.6
  script: tox -e py36-django19
py27-django110:
  stage: test
  image: python:2.7
  script: tox -e py27-django110
py34-django110:
  stage: test
  image: python:3.4
  script: tox -e py34-django110
py35-django110:
  stage: test
  image: python:3.5
  script: tox -e py35-django110
py36-django110:
  stage: test
  image: python:3.6
  script: tox -e py36-django110
