language: python
sudo: false

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27-django18
    - python: 3.3
      env: TOX_ENV=py33-django18
    - python: 3.4
      env: TOX_ENV=py34-django18
    - python: 3.5
      env: TOX_ENV=py35-django18
    - python: 3.6
      env: TOX_ENV=py36-django18
# commented out, see https://code.djangoproject.com/ticket/27544#comment:9
#    - python: 2.7
#      env: TOX_ENV=py27-django19
#    - python: 3.4
#      env: TOX_ENV=py34-django19
#    - python: 3.5
#      env: TOX_ENV=py35-django19
#    - python: 3.6
#      env: TOX_ENV=py36-django19
    - python: 2.7
      env: TOX_ENV=py27-django110
    - python: 3.4
      env: TOX_ENV=py34-django110
    - python: 3.5
      env: TOX_ENV=py35-django110
    - python: 3.6
      env: TOX_ENV=py36-django110

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
